apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "podlock.fullname" . }}-controller-webhook-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podlock.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "podlock.fullname" . }}-controller-webhook-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podlock.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  secretName: {{ include "podlock.fullname" . }}-controller-webhook-tls
  dnsNames:
    - {{ include "podlock.fullname" . }}-controller-webhook.{{ .Release.Namespace }}.svc
    - {{ include "podlock.fullname" . }}-controller-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "podlock.fullname" . }}-controller-webhook-issuer