apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podlock.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "podlock.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      {{ include "podlock.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      labels:
        {{ include "podlock.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      containers:
        - command:
            - /controller
          args:
            - -leader-elect
            - -health-probe-bind-address=:8081
          image: '{{ template "system_default_registry" . }}{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}'
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          name: controller
          securityContext:
            {{ include "podlock.securityContext" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- if and .Values.controller .Values.controller.resources }}
          resources:
{{ toYaml .Values.controller.resources | indent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: "/tmp/k8s-webhook-server/serving-certs"
              name: webhook-tls
              readOnly: true
      volumes:
        - name: webhook-tls
          secret:
            secretName: {{ include "podlock.fullname" . }}-controller-webhook-tls
      serviceAccountName: {{ include "podlock.fullname" . }}-controller
      terminationGracePeriodSeconds: 10
