apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "podlock.fullname" . }}-controller-metrics-reader
  labels:
    {{ include "podlock.labels" .| nindent 4 }}
    app.kubernetes.io/component: controller
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
