---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "podlock.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "podlock.fullname" . }}-controller
rules:
- apiGroups:
  - podlock.kubewarden.io
  resources:
  - landlockprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podlock.kubewarden.io
  resources:
  - landlockprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - podlock.kubewarden.io
  resources:
  - landlockprofiles/status
  verbs:
  - get
  - patch
  - update
